version: '3.8'
services:
  read-db:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: 'vf-read-db'
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  event-store:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  # api: 
  #   build: .
  #   container_name: api
  #   ports:
  #     - 3000:3000
  #   command: npm run start:dev
  #   depends_on:
  #     - read-db
  #     - rabbitmq
  #     - event-store
volumes: 
  mongodbdata:
  rabbitmqdata:
